import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin_dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className=" w-screen h-screen grid grid-cols-10 grid-rows-10">
          <nav className=" row-start-1 row-end-2 col-start-3 col-end-11 drop-shadow-lg">navbar</nav>
          <section className=" row-start-1 row-end-11 col-start-1 col-end-3">sidebar</section>
          <main className="bg-[#F5F6FA] row-start-2 row-end-11 col-start-3 col-end-11">main</main>
        </div>
      </body>
    </html>
  );
}