import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import DashLayot from "@/components/dashboardUI/DashLayot";
import { AuthProvider } from "@/context/AuthProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin_dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <DashLayot>{children}</DashLayot>
        </AuthProvider>


      </body>
    </html>
  );
}