import { Geist, Geist_Mono } from "next/font/google";
import "./main.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Preloader from "@/components/layout/PreLoader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div id="smooth-wrapper" className="manrope bg-[#171614] py-4">
          <Preloader />
          <div id="smooth-content" className="flex flex-col min-h-screen">
            <Header/>
            <main className="flex-1">{children}</main>
            <Footer/>
          </div>
        </div>
      </body>
    </html>
  );
}
